
// DISABLED: ES_ADD_ADHOC_TASKS-PLN:1
//if ((appMatch('Planning/Development/*/*')|| appMatch('Planning/Non Development/*/*')|| appMatch('Planning/Subdivision/*/*')|| appMatch('Planning/Variance/*/*')) && AInfo['ParcelAttribute.RIVER DISTRICT'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','River District Design Review', ' ','RHURLEY');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PLN:2
//if ((appMatch('Planning/Development/*/*')|| appMatch('Planning/Non Development/*/*')|| appMatch('Planning/Subdivision/*/*')|| appMatch('Planning/Variance/*/*')) && AInfo['ParcelAttribute.DTDR OVERLAY'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Downtown Design Review',' ','SVRTUNSKI');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PLN:3
//if ((appMatch('Planning/Development/*/*')|| appMatch('Planning/Non Development/*/*')|| appMatch('Planning/Subdivision/*/*')|| appMatch('Planning/Variance/*/*')) && AInfo['ParcelAttribute.HRC OVERLAY'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','HRC Overlay',' ','ACOLE');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PLN:4
//if ((appMatch('Planning/Development/*/*')|| appMatch('Planning/Non Development/*/*')|| appMatch('Planning/Subdivision/*/*')|| appMatch('Planning/Variance/*/*')) && AInfo['ParcelAttribute.FLOOD PLAIN'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Flood',' ','STWTTBD');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PLN:5
//if ((appMatch('Planning/Development/*/*')|| appMatch('Planning/Non Development/*/*')|| appMatch('Planning/Subdivision/*/*')) && AInfo['ParcelAttribute.STEEP SLOPE'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Steep Slope',' ','PZPRTBD');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PLN:6
//if ((appMatch('Planning/Development/*/*')|| appMatch('Planning/Non Development/*/*')|| appMatch('Planning/Subdivision/*/*')|| appMatch('Planning/Variance/*/*')) && AInfo['ParcelAttribute.LANDMARK'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Landmark',' ','ACOLE');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PLN:7
//if ((appMatch('*/*/Annexation/*') || appMatch('*/*/Landmark/*') || appMatch('*/*/Map Amendments/*') || appMatch('*/*/Rezoning/*') || appMatch('*/*/Text Amendments/*'))) {
//	addAdHocTask('ADHOC TASKS','NC Dept of Cultural Resources',' ','ACOLE');
//	}

