
// DISABLED: ES_ADD_ADHOC_TASKS-SRV:1
//if ((appMatch('Services/Complaint-Enforcement/*/*')) && AInfo['ParcelAttribute.RIVER DISTRICT'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','River District Design Review', ' ','RHURLEY');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-SRV:2
//if ((appMatch('Services/Complaint-Enforcement/*/*')) && AInfo['ParcelAttribute.DTDR OVERLAY'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Downtown Design Review',' ','SVRTUNSKI');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-SRV:3
//if ((appMatch('Services/Complaint-Enforcement/*/*')) && AInfo['ParcelAttribute.HRC OVERLAY'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','HRC Overlay',' ','ACOLE');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-SRV:4
//if ((appMatch('Services/Complaint-Enforcement/*/*')) && AInfo['ParcelAttribute.STEEP SLOPE'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Steep Slope',' ','PZPRTBD');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-SRV:5
//if ((appMatch('Services/Complaint-Enforcement/*/*')) && AInfo['ParcelAttribute.LANDMARK'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Landmark',' ','ACOLE');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-SRV:6
//if ((appMatch('Services/Complaint-Enforcement/*/*')) && AInfo['ParcelAttribute.FLOOD PLAIN'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Flood',' ','STWTTBD');
//	}

