
// DISABLED: ES_ADD_ADHOC_TASKS-PERMITS:1
//if ((appMatch('Permits/*/New Building/*')||appMatch('Permits/*/Existing Building/*')||appMatch('*/*/Remodel/*')|| appMatch('*/*/Manufactured Home/*')|| appMatch('*/*/Demolition/*')|| appMatch('*/*/Addition/*')|| appMatch('*/*/Accessory Structure/*')||appMatch('Permits/*/New/*')|| appMatch('Permits/*/Construction Trailer/*')|| appMatch('Permits/*/Site Work/*')|| appMatch('Permits/Sign/Stand Alone/*')) && AInfo['ParcelAttribute.RIVER DISTRICT'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','River District Design Review', ' ','RHURLEY');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PERMITS:2
//if ((appMatch('Permits/*/New Building/*')||appMatch('Permits/*/Existing Building/*')||appMatch('Permits/Outdoor Vendor/*/*')|| appMatch('*/*/Reroof/*')|| appMatch('*/*/Remodel/*')|| appMatch('*/*/Manufactured Home/*')|| appMatch('*/*/Demolition/*')|| appMatch('*/*/Addition/*')|| appMatch('*/*/Accessory Structure/*')||appMatch('Permits/*/New/*')|| appMatch('Permits/*/Construction Trailer/*')|| appMatch('Permits/*/Site Work/*')|| appMatch('Permits/Sign/Stand Alone/*')) && AInfo['ParcelAttribute.DTDR OVERLAY'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Downtown Design Review',' ','SVRTUNSKI');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PERMITS:3
//if ((appMatch('Permits/*/New Building/*')||appMatch('Permits/*/Existing Building/*')||appMatch('*/*/Reroof/*')|| appMatch('*/*/Remodel/*')|| appMatch('*/*/Manufactured Home/*')|| appMatch('*/*/Demolition/*')|| appMatch('*/*/Addition/*')|| appMatch('*/*/Accessory Structure/*')||appMatch('Permits/*/New/*')|| appMatch('Permits/*/Construction Trailer/*')||appMatch('Permits/*/Annual Maintenance/*') || appMatch('Permits/*/Site Work/*')|| appMatch('Permits/Sign/Stand Alone/*')) && AInfo['ParcelAttribute.HRC OVERLAY'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','HRC Overlay',' ','ACOLE');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PERMITS:4
//if ((appMatch('Permits/*/New Building/*')||appMatch('Permits/*/Existing Building/*')||appMatch('*/*/Reroof/*')|| appMatch('*/*/Remodel/*')|| appMatch('*/*/Manufactured Home/*')|| appMatch('*/*/Demolition/*')|| appMatch('*/*/Addition/*')|| appMatch('*/*/Accessory Structure/*')||appMatch('Permits/*/New/*')|| appMatch('Permits/*/Construction Trailer/*')|| appMatch('Permits/*/Site Work/*')|| appMatch('Permits/Sign/Stand Alone/*')) && AInfo['ParcelAttribute.FLOOD PLAIN'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Flood',' ','STWTTBD');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PERMITS:5
//if ((appMatch('Permits/*/New Building/*')||appMatch('Permits/*/Existing Building/*')||appMatch('*/*/Manufactured Home/*')|| appMatch('*/*/Addition/*')|| appMatch('*/*/Accessory Structure/*')|| appMatch('Permits/*/New/*')|| appMatch('Permits/*/Site Work/*')) && AInfo['ParcelAttribute.STEEP SLOPE'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Steep Slope',' ','PZPRTBD');
//	}

// DISABLED: ES_ADD_ADHOC_TASKS-PERMITS:6
//if ((appMatch('Permits/*/New Building/*')||appMatch('Permits/*/Existing Building/*')||appMatch('*/*/Reroof/*')|| appMatch('*/*/Remodel/*')|| appMatch('*/*/Manufactured Home/*')|| appMatch('*/*/Demolition/*')|| appMatch('*/*/Addition/*')|| appMatch('*/*/Accessory Structure/*')||appMatch('Permits/*/New/*')|| appMatch('Permits/*/Construction Trailer/*')|| appMatch('Permits/*/Site Work/*') || appMatch('Permits/*/Annual Maintenance/*') || appMatch('Permits/Sign/*/*')) && AInfo['ParcelAttribute.LANDMARK'] == 'Yes') {
//	addAdHocTask('ADHOC TASKS','Landmark',' ','ACOLE');
//	}

