
// DISABLED: ES_COM_NEW_FEES:1
//if (AInfo['Building'] != 0) {
//	updateFee('C_001','COM_BLD','FINAL',AInfo['Building'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:2
//if (AInfo['Electrical'] != 0) {
//	updateFee('C_002','COM_BLD','FINAL',AInfo['Electrical'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:3
//if (AInfo['Mechanical'] != 0) {
//	updateFee('C_003','COM_BLD','FINAL',AInfo['Mechanical'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:4
//if (AInfo['Plumbing'] != 0) {
//	updateFee('C_004','COM_BLD','FINAL',AInfo['Plumbing'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:5
//if (AInfo['Gas Piping'] != 0) {
//	updateFee('C_005','COM_BLD','FINAL',AInfo['Gas Piping'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:6
//if (AInfo['Refrigeration'] != 0) {
//	updateFee('C_006','COM_BLD','FINAL',AInfo['Refrigeration'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:7
//if (AInfo['Hood System'] != 0) {
//	updateFee('C_007','COM_BLD','FINAL',AInfo['Hood System'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:8
//if (AInfo['Fire Sprinkler'] != 0) {
//	updateFee('F_001','COM_BLD','FINAL',AInfo['Fire Sprinkler'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:9
//if (AInfo['Fire Alarms'] != 0) {
//	updateFee('F_002','COM_BLD','FINAL',AInfo['Fire Alarms'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:10
//updateFee('C_009','COM_BLD','FINAL',AInfo['Total Cost of Work'],'N');
// DISABLED: ES_COM_NEW_FEES:11
//updateFee('CFIRE','COM_BLD','FINAL',AInfo['Total SqFt'],'N');
// DISABLED: ES_COM_NEW_FEES:12
//updateFee('TRN_CDW','SITE','FINAL',AInfo['Entrance Cuts'],'N');
// DISABLED: ES_COM_NEW_FEES:13
//if (AInfo['Disturbed Area'] == '<10ksf') {
//	updateFee('PW_GR01','SITE','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:14
//if (AInfo['Disturbed Area'] == '10ksf-1ac') {
//	updateFee('PW_GR02','SITE','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:15
//if (AInfo['Disturbed Area'] == '>/=1ac') {
//	updateFee('PW_GR03','SITE','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:16
//if (AInfo['Disturbed Area'] == '>/=1ac') {
//	updateFee('PW_GR04','SITE','FINAL',parseInt(AInfo['Acres Land Disturbed']),'N');
//	comment('Acres Rounded = '+parseInt(AInfo['Acres Land Disturbed']));
//	}

// DISABLED: ES_COM_NEW_FEES:17
//if (AInfo['New Address'] == 'Yes' &&  AInfo['Number of Units'] > 0) {
//	updateFee('ADD01','COM_BLD','FINAL',AInfo['Number of Units'],'N');
//	}

// DISABLED: ES_COM_NEW_FEES:18
//if (AInfo['Seeking LEED cert'] == 'Yes') {
//	updateFee('C_010','COM_BLD','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:19
//if (AInfo['Economic Development Grant'] == 'Yes') {
//	updateFee('C_010','COM_BLD','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:20
//if (AInfo['Affordable Housing'] == 'Yes') {
//	updateFee('C_010','COM_BLD','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:21
//if (AInfo['Public Funding'] == 'Yes') {
//	updateFee('C_010','COM_BLD','FINAL',1,'N');
//	}

// DISABLED: ES_COM_NEW_FEES:22
//updateFee('TECH','RES_NEW','FINAL',1,'N');

